name: "docs-linter"
description: "Standardize documentation and prose with different linters"

inputs:
  file-patterns:
    description: “Patterns to look in source files, comma separated”
    required: true

  license:
    description: “Open-source license to enforce”
    default: "mit"
    required: true

runs:
  using: "composite"
  steps:
      - name: Check typos everywhere
        uses: crate-ci/typos@v1.20.8

      - name: Lint documentation
        shell: bash
        run: ${{ github.action_path }}/../src/docs-linter.sh $GITHUB_WORKSPACE

      - name: Lint Bash Scripts
        shell: bash
        run: ${{ github.action_path }}/../src/bash-linter.sh $GITHUB_WORKSPACE

      - name: Check licenses on source files
        shell: bash
        run: ${{ github.action_path }}/../src/license-enforcer.sh $GITHUB_WORKSPACE ${{ inputs.file-patterns }} ${{ inputs.license }}
