name: "prepare-ghpages"
description: "Prepare static assets compatible with Github Pages"

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 22

    - name: Build docs with Vitepress
      shell: bash
      run: ${{ github.action_path }}/build-docs.sh $GITHUB_WORKSPACE

    - name: Configure Github Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

    - name: Upload assets Github Pages assets
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: docs/.vitepress/dist
