name: "prepare-ghpages"
description: "Prepare static assets compatible with Github Pages"

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24

    - name: Build docs with Vitepress
      shell: bash
      run: ${{ github.action_path }}/build-docs.sh $GITHUB_WORKSPACE

    - name: Configure Github Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

    - name: Upload assets Github Pages assets
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: docs/.vitepress/dist
