name: "typos-checker"
description: "Inspect source files for typos and spelling"

runs:
  using: "composite"
  steps:
    - name: Check typos everywhere
      uses: crate-ci/typos@0d9e0c2c1bd7f770f6eb90f87780848ca02fc12c # v1.26.8
