name: "typos-checker"
description: "Inspect source files for typos and spelling"

runs:
  using: "composite"
  steps:
    - name: Check typos everywhere
      uses: crate-ci/typos@945d407a5fc9097f020969446a16f581612ab4df # v1.24.5
