name: "typos-checker"
description: "Inspect source files for typos and spelling"

runs:
  using: "composite"
  steps:
    - name: Check typos everywhere
      uses: crate-ci/typos@49d37361a04c8119928f7463881fbc32a1c1abd0 # v1.22.1
