name: "typos-checker"
description: "Inspect source files for typos and spelling"

runs:
  using: "composite"
  steps:
    - name: Check typos everywhere
      uses: crate-ci/typos@51f257b946f503b768e522781f56e9b7b5570d48 # v1.29.7
