name: "check-licenses"
description: "Check open-source licence on source code headers"

inputs:
  file-patterns:
    description: “Patterns to look in source files, comma separated”
    required: true

  license:
    description: “Open-source license to enforce”
    required: true

runs:
  using: "composite"
  steps:
    - name: Check licenses on source files
      shell: bash
      run: ${{ github.action_path }}/license-checker.sh $GITHUB_WORKSPACE ${{ inputs.file-patterns }} ${{ inputs.license }}
